### ISSUE TITLE
@PostMapping -> Path "/users" -> no need to add create to the path, no actions on the path, only resources

### ISSUE THREAD

**Issue by giselacostamindera** [TiagoPadrao18/users-db#1]
https://github.com/TiagoPadrao18/users-db/blob/6152b5ce3d001dd1518c5fa7ceb7bd566447a634/src/main/java/com/usersDb/usersDb/controller/UserController.java#L19

If it is a REST API, method POST and /users -> we know it will create a user because that is the architecture style defined for REST API and every programmer should follow it

If it is a REST API, method PUT and /users/{userId} ->We know we are updating the user with the ID defined on userId

If it is a REST API, method DELETE and /users/{userId} ->We know we are deleting the user with the ID defined on userId

If it is a REST API, method GET and /users/{userId} ->We know we are getting the user with the ID defined on userId

If it is a REST API, method GET and /users ->We know we are getting all users

**Comment by TiagoPadrao18** [comment]
so, for example, in method Delete, should be @DeleteMapping("{userId}")?

**Comment by TiagoPadrao18** [comment]
fixed.
