### ISSUE TITLE
Great work choosing the HTTPStatus, since you are learning, always google for the HTTPSTatus code meaning

### ISSUE THREAD

**Issue by giselacostamindera** [TiagoPadrao18/users-db#3]
https://github.com/TiagoPadrao18/users-db/blob/6152b5ce3d001dd1518c5fa7ceb7bd566447a634/src/main/java/com/usersDb/usersDb/controller/UserController.java#L20

201 Created
The HTTP 201 Created success status response code indicates that the request has succeeded and has led to the creation of a resource. The new resource, or a description and link to the new resource, is effectively created before the response is sent back and the newly created items are returned in the body of the message, located at either the URL of the request, or at the URL in the value of the [Location](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) header.

**Comment by TiagoPadrao18** [comment]
Thankss, i always go to http.cat website for HTTPStatus code's meaning hahah!
