### ISSUE TITLE
UsersController should call UsersService,  and UsersService should call UsersRepository

### ISSUE THREAD

**Issue by giselacostamindera** [TiagoPadrao18/users-db#4]
https://github.com/TiagoPadrao18/users-db/blob/6152b5ce3d001dd1518c5fa7ceb7bd566447a634/src/main/java/com/usersDb/usersDb/controller/UserController.java#L22C21-L22C35

Keep in mind the architecture, on the UsersService we can do some logic and throw some custom exceptions.

**Comment by TiagoPadrao18** [comment]
done.
